@id = c912b745-7baf-4083-bf4d-221d3c4339a7

PUT http://localhost:5182/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sushi",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}