@id = 3cf5bcb6-e4d3-4405-a6db-0093c544be5d

PUT http://localhost:5182/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sushi",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}